### ISSUE TITLE
请加入上海交大镜像源

### ISSUE THREAD

**Issue by HaujetZhao** [13528080556/pip_setting#2]
每次安装 python 第一个安装的第三包就是 pip-setting，非常方便好用。

最近在 [阿里的文档](https://alibaba-damo-academy.github.io/FunASR/en/runtime/onnxruntime_python.html) 中，发现他们建议下载时使用 `-i https://mirror.sjtu.edu.cn/pypi/web/simple` ，我试了之后，确实很快，比清华源、阿里源的速度快多了。

**Comment by qq1u** [comment]
已添加
